### ISSUE TITLE
Diff output looks broken

### ISSUE THREAD

**Issue by KhalilSantana** [twpayne/chezmoi#1332] opened 2021-08-07 03:53 UTC
## What exactly are you trying to do?

The output of `chezmoi diff` looks broken, as it contains uninterpreted/raw escape/control characters.

![no-flags](https://user-images.githubusercontent.com/26551202/128586910-98c160aa-4f77-4f57-b73b-fa6ffdf8c00f.png)

## What have you tried so far?

Using `--no-pager` makes it look OK, as well as piping `chezmoi diff` into another program, such as `cat(1)`.

Using no `--no-pager`: 
![no-pager](https://user-images.githubusercontent.com/26551202/128586970-506acd81-be10-42ae-8269-7b8a9e9d745a.png)

Piping to `cat(1)`:
![pipe-to-cat](https://user-images.githubusercontent.com/26551202/128586955-afa0867d-88c9-4efa-8ff9-430a66763111.png)

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.

## Output of any commands you've tried with `--verbose` flag

Not applicable, as there's no difference using --verbose for this command.

## Output of `chezmoi doctor`

```console
% chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              v2.1.4, built at 2021-08-05T11:57:28Z
ok        os-arch              linux/amd64
info      config-file          /home/khalil/.config/chezmoi/chezmoi.toml does not exist
ok        source-dir           /home/khalil/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries found in /home/khalil/.local/share/chezmoi
ok        dest-dir             /home/khalil is a directory
ok        shell                found /usr/bin/zsh
ok        editor               found /usr/bin/nvim
ok        git-cli              found /usr/bin/git, version 2.32.0
ok        merge-cli            found /usr/bin/vimdiff
ok        age-cli              age not found in $PATH
ok        gnupg-cli            found /usr/bin/gpg, version 2.2.29
info      1password-cli        op not found in $PATH
info      bitwarden-cli        bw not found in $PATH
info      gopass-cli           gopass not found in $PATH
ok        keepassxc-cli        found /usr/bin/keepassxc-cli, version 2.6.6
info      keepassxc-db         not set
info      lastpass-cli         lpass not found in $PATH
info      pass-cli             pass not found in $PATH
info      vault-cli            vault not found in $PATH
info      secret-cli           not set
```

## Additional context

I'm not sure how long this has been like this, and whether this is a chezmoi bug or some broken configuration file, shell setting, or other environment factors, as such I'm submitting this as a support request.

**Comment by twpayne** [comment] 2021-08-07 09:42
Indeed, those are ANSI control sequences that chezmoi (and other programs) uses to set colors. In your case, it looks like the default pager (`less`, unless you have configured something different) is breaking the interpretation of those control characters.

Some options for you:
* Investigate why your pager is breaking the interpretation of terminal control sequences.
* Verify that your `TERM` environment variable is set correctly and that your `termcap` database is correct.
* Tell chezmoi not to use a pager by either setting `pager = ""` in the config file or using the `--no-pager` flag.
* Tell chezmoi not to colorize the output by either setting `color = false` in the config file or using the `--color=false` flag.

> I'm not sure how long this has been like this, and whether this is a chezmoi bug or some broken configuration file, shell setting, or other environment factors, as such I'm submitting this as a support request.

Given that chezmoi has thousands of users and no one else has reported this, it's almost certainly specific to your setup.

**Comment by KhalilSantana** [comment] 2021-08-07 17:19
Environment:
```
% env | egrep -i "pager|term|less"
COLORTERM=yes
LESSHISTFILE=/home/khalil/.cache/less/history
LESSKEY=/home/khalil/.config/less/lesskey
TERM=xterm-256color
PAGER=less
LESS_TERMCAP_mb=
LESS_TERMCAP_md=
LESS_TERMCAP_me=
LESS_TERMCAP_se=
LESS_TERMCAP_so=
LESS_TERMCAP_ue=
LESS_TERMCAP_us=
```
I've tried setting TERM to the values below and the issue persists:
* linux
* xterm
* konsole
* dumb

Then I've tried a couple of terminals, listed below, same issue:
* konsole & yakuake
* alacritty
* a real tty (ctrl+alt+f2)

> and that your termcap database is correct.

How can I do this? Searching for such package yields one result (from the Arch AUR), installing it doesn't seem to fix it either.

**Comment by twpayne** [comment] 2021-08-07 22:58
Thanks for the extra info.

`chezmoi diff` generates a diff including terminal control sequences and pipes it into your pager. It doesn't do anything more sophisticated than that.

The following should help isolate the problem. What is the result of the following commands?

* `ls --color=always` (you should get a directory listing with some colors in it).
* `ls --color=always | less` (you should a directory listing with some colors in it, but with one entry per line).

I strongly suspect the problem is due to the `LESS_TERMCAP_*` environment variables that you have set. These cause `less` to override various terminal control sequences. What are the results of the following commands?

* `for cap in mb md me se so ue us; do unset LESS_TERMCAP_$cap; done && ls --color=always | less`
* `for cap in mb md me se so ue us; do unset LESS_TERMCAP_$cap; done && chezmoi diff`

**Comment by KhalilSantana** [comment] 2021-08-07 23:55
> I strongly suspect the problem is due to the LESS_TERMCAP_* environment variables that you have set.

I don't believe I've set any such variables, see the environment section on my previous comment, if I did set them, they should be listed there, correct? Or I'm I overlooking something?

Regardless, here are the tests you've requested:

>  What is the result of the following commands?
> ls --color=always (you should get a directory listing with some colors in it).

The output looks OK:
![image](https://user-images.githubusercontent.com/26551202/128616398-113ee8cd-b8a4-47d0-9c4e-8e761b8595d5.png)

> ls --color=always | less (you should a directory listing with some colors in it, but with one entry per line).

This one looks broken:
![image](https://user-images.githubusercontent.com/26551202/128616406-6d1afac5-d92b-43d5-b95d-afa034b8bbe6.png)

> for cap in mb md me se so ue us; do unset LESS_TERMCAP_$cap; done && ls --color=always | less

Slightly different looking broken (notice the colors have changed):
![image](https://user-images.githubusercontent.com/26551202/128616422-0cc75231-f3cf-4abf-8fbb-13e6a93c2918.png)

> for cap in mb md me se so ue us; do unset LESS_TERMCAP_$cap; done && chezmoi diff

Also weird-looking: 
![image](https://user-images.githubusercontent.com/26551202/128616450-57a0e66b-d505-4809-b2ab-10917b05f70d.png)

___

So it seems that my pager (less) is broken in general, for some reason.

**Comment by twpayne** [comment] 2021-08-08 15:02
> So it seems that my pager (less) is broken in general, for some reason.

As we've narrowed it down to being your pager, not chezmoi, I'll close this issue now.

**Closed by twpayne** 2021-08-08 15:02 UTC
Labels: support

**Comment by twpayne** [comment] 2021-09-26 20:47
After reading [this post](https://fasterthanli.me/articles/a-terminal-case-of-linux) I think you need to set the `LESS` environment variable to `-R`, i.e.

    export LESS=-R

Explanation:

The pager `less` needs the `-R`/`--RAW-CONTROL-CHARS` option to be set to pass terminal control characters through, otherwise it mangles them. The `LESS` environment variable contains extra options to `less`. See [`man less`](https://linux.die.net/man/1/less) and specifically the documentation on the `-R` option and the `LESS` environment variable for more details.

cc @georgebushdown
