### ISSUE TITLE
Trouble finding `.chezmoiversion` when `.chezmoiroot` is implemented

### ISSUE THREAD

**Issue by jussapaavo** [twpayne/chezmoi#1684] opened 2021-11-28 21:27 UTC
## Describe the bug

I've implemented the `.chezmoiroot` and move all my chezmoi files to a subdirectory called `src`. I also moved `.chezmoiversion` to this new directory.

But now when I'm going to my other machine with earlier version of chezmoi and run the usual `chezmoi update` command, the files are moved to this new subdirectory and at the same time `.chezmoiversion` is not seen anymore by the earlier chezmoi version and thus not enforcing the version restrictions.

## To reproduce

1. Implement `.chezmoiroot` and move all managed files to a subdirectory
2. Implement `.chezmoiversion` and set it to >= 2.8.0
3. Downgrade chezmoi to <2.8.0
4. Run `chezmoi apply`
-> Everything is applied, even though .chezmoiversion has restrictions

## Expected behavior

Do not apply changes, if the machine does not have correct chezmoi version.

## Additional context

I suggest that `.chezmoiversion` should be kept in the root of the repository, same place as `.chezmoiroot` to allow backwards compatibility.

**Comment by twpayne** [comment] 2021-11-29 01:08
I think this is a valid bug. What was the reason for closing it?

**Comment by felipecrs** [comment] 2021-11-29 01:37
I will try to reproduce it here too.

**Comment by felipecrs** [comment] 2021-11-29 03:58
I can confirm the bug:

![image](https://user-images.githubusercontent.com/29582865/143806623-f5ce17ba-9f05-4c37-8d36-c9708715c036.png)

**Closed** 2021-11-29 11:50 UTC
Labels: bug
