### ISSUE TITLE
.chezmoiroot not working in GitHub Actions

### ISSUE THREAD

**Issue by futabooo** [twpayne/chezmoi#2865] opened 2023-03-16 14:34 UTC
## Describe the bug

`.chezmoiroot` seems to be ignored when using one line install with GitHub Actions

## To reproduce

add `.chezmoiroot`
```
home
```

add `home/.chezmoiscripts/run_once_echo.sh.tmpl`

```
{{ if eq .chezmoi.os "darwin" -}}
#!/usr/bin/env bash

set -euo pipefail

echo {{ .chezmoi.sourceDir }}

{{ end -}}

```

add `.github/workflows/test.yaml`
```
name: Test install

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub UseName'
        required: true
        type: string

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
    - name: Run install
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${{ inputs.username }} 
```

when dispatch Test install workflow, echo `/Users/runner/.local/share/chezmoi`

## Expected behavior

echo `/Users/runner/.local/share/chezmoi/home`

**Comment by twpayne** [comment] 2023-03-16 17:11
This should on print something when running on `macos-latest`. It does not print anything on `ubuntu-latest` because the script is empty on Linux. Is this the behavior you observe?

**Comment by twpayne** [comment] 2023-04-16 18:47
I tried to reproduce this issue in #2930 but was not successful. There should not be anything special about GitHub Actions.

Could you share a link your dotfiles repo that demonstrates the problem and/or a minimal example that demonstrates the problem?

**Comment by futabooo** [comment] 2023-04-17 00:40
thank you for your research.
reproducing this in my dotfiles repository.
https://github.com/futabooo/dotfiles

here is the job that is failing due to path issues
https://github.com/futabooo/dotfiles/actions/runs/4456521319/jobs/7827020770

**Comment by twpayne** [comment] 2023-04-17 18:27
> here is the job that is failing due to path issues
> https://github.com/futabooo/dotfiles/actions/runs/4456521319/jobs/7827020770

This is failing with the message "Error: No Brewfile found". This error is not due to chezmoi.



> thank you for your research.
> reproducing this in my dotfiles repository.
> https://github.com/futabooo/dotfiles

I tried to duplicate the problem with:

```console
$ podman pull ubuntu:latest
...
$ podman run -it ubuntu:latest /bin/sh
...
# apt update && apt install -y curl sudo
...
# sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply futabooo
info found version 2.33.1 for latest/linux/amd64
info installed ./bin/chezmoi
Installing packages ...
info: latest release: 0.7.1
info: found valid target: x86_64-unknown-linux-musl
info: downloading: sheldon-0.7.1-x86_64-unknown-linux-musl.tar.gz
######################################################################## 100.0%
info: installed: /usr/local/bin/sheldon
...
```

This seemed to install your dotfiles correctly.

Do you have another way of reproducing the problem?

**Comment by bradenhilton** [comment] 2023-04-18 17:09
Have you tried `echo`ing the path it is attempting to find the Brewfile in?

**Comment by futabooo** [comment] 2023-04-19 00:49
https://github.com/twpayne/chezmoi/issues/2865#issuecomment-1472991639

>print /Users/runner/.local/share/chezmoi when macos-latest.
>expecting /Users/runner/.local/share/chezmoi/home

**Comment by halostatue** [comment] 2023-04-19 04:12
I just recently adopted the use of a `.chezmoiroot` and I’m seeing the correct details in the various `$CHEZMOI*` variables that are exported to scripts or under `chezmoi cd`:

```console
❯ set -a | grep CHEZ
CHEZMOI_SOURCE_DIR /Users/austin/.local/share/chezmoi/home
CHEZMOI_VERSION_BUILT_BY goreleaser
CHEZMOI_VERSION_COMMIT bc4478d84f59ea38084cf7e58b9226278d0e046d
CHEZMOI_VERSION_DATE 2023-04-07T22:36:48Z
CHEZMOI_VERSION_VERSION 2.33.1
CHEZMOI_WORKING_TREE /Users/austin/.local/share/chezmoi
```

These variables map from `{{ .chezmoi.sourceDir }}`, `{{ .chezmoi.version.* }}`, and `{{ chezmoi.workingTree }}`.

**Comment by aarondill** [comment] 2023-05-08 12:06
This is not special to github actions. I've had issues with this exact problem in the past when cloning to a new machine.

**Comment by aarondill** [comment] 2023-05-08 13:30
Repro: 

# This resets your chezmoi state data!
This also will add to your git repository!

```
$ cat "$(chezmoi source-path)/../.chezmoiroot"
source
$ cd "$(chezmoi source-path)"
$ mkdir -p "./.chezmoiscripts" # no effect if exists
$ cd "./.chezmoiscripts"
$ printf '#!/usr/bin/env sh\necho "CHEZMOI_SOURCE_DIR  = $CHEZMOI_SOURCE_DIR"' >| run_once_before_00-aa-echo-source-path.sh
$ git add run_once_before_00-echo-source-path.sh
$ git commit -m 'REPRO: twpayne/chezmoi#2865'
$ git push
...

$ # New machine (or VM), OR:
$ # If you use this, be *very* careful. This will erase working changes and I am not responsible for what you lose.
$ chezmoi purge --force --binary

$ # make sure git is setup if you are on a new machine
$ # you will probably use `gh`, but any way should work
$ export REPO=user/repo # your dotfiles repo here
$ BINDIR="$HOME/.local/bin" sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply "$REPO"
...
CHEZMOI_SOURCE_DIR  =  /home/aaron/.local/share/chezmoi
...
$ chezmoi state reset
$ # Same as before, but this time the source-dir already exists
$ BINDIR="$HOME/.local/bin" sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply "$REPO"
...
CHEZMOI_SOURCE_DIR  =  /home/aaron/.local/share/chezmoi/souce
...
```
That should be `/home/aaron/.local/share/chezmoi/source`, but it's not respecting `.chezmoiroot`. Running it a second time, it works, because `~/.local/share/chezmoi/.chezmoiroot` already exists when chezmoi starts.


I've encountered this a few times in my own usage, but I had not gotten around to submitting a report yet.

**Comment by aarondill** [comment] 2023-05-08 13:37
Note, if on a new machine, you must install `git` and `curl` before running the `sh $(...)` command

**Comment by aarondill** [comment] 2023-05-11 19:35
Woo! Just compiled and tested this! Works amazing! I can finally use the one liner (when it's released) to install and run chezmoi (after setting up `gh` and `git`). Would love to have this in a release soon so I don't have to compile it fresh on a new machine (`go` is like 1.18.something in ubuntu repos)

**Comment by twpayne** [comment] 2023-05-11 20:11
Thanks to @4ooc for the fix!

2.33.5 was just released with the fix :)

GitHub has a bug where the release notes incorrectly assign credit. I'll report this to GitHub.

**Comment by aarondill** [comment] 2023-05-15 00:06
This has been fixed, if reentering chezmoi in a script (ie `chezmoi source-path`), but the `$CHEZMOI_SOURCE_DIR` environment variable still disrespects `.chezmoiroot`

**Comment by aarondill** [comment] 2023-05-15 00:11
This can still be seen running the above repro:
```console
sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply aarondill
...
CHEZMOI_SOURCE_DIR  = /home/aaron/.local/share/chezmoi
...
```

**Comment by aarondill** [comment] 2023-05-15 02:10
I didn't notice this until I updated my scripts because the advice on #2993

**Comment by aarondill** [comment] 2023-05-15 12:23
When cloning to a new machine, my (personal) configuration outputs the following, while both should be the same
```console
> chezmoi init ...
...
CHEZMOI_SOURCE_DIR = /home/aaron/.local/share/chezmoi
chezmoi source-path = /home/aaron/.local/share/chezmoi/source
...
```

**Comment by twpayne** [comment] 2023-05-15 17:26
Thanks for testing and reporting. #3001 should fix it.

**Closed by twpayne** 2023-05-15 17:26 UTC
Labels: bug

**Comment by aarondill** [comment] 2023-05-15 21:38
```console
CHEZMOI_SOURCE_DIR = /home/aaron/.local/share/chezmoi/source
chezmoi source-path = /home/aaron/.local/share/chezmoi/source
```
