### ISSUE TITLE
doc: sequence diagram in dark mode

### ISSUE THREAD

**Issue by FreeMasen** [twpayne/chezmoi#3175] opened 2023-08-14 14:46 UTC
## Describe the bug

The font in the sequence diagram is unreadable when dark mode is turned on (this is selected based on the operating system setting the user has chosen)

## To reproduce

Turn on dark mode while browsing the docs

## Expected behavior

Fonts should be toggled to a lighter color when the theme changes

## Additional context

![Screenshot-6](https://github.com/twpayne/chezmoi/assets/6232026/9beb3904-da90-4d13-bd45-486fb7e54bba)

**Comment by twpayne** [comment] 2023-08-14 20:04
Thanks for reporting this. This should have been fixed with https://github.com/twpayne/chezmoi/pull/2309. What browser and operating system are you using?

**Comment by FreeMasen** [comment] 2023-08-14 20:14
Firefox 116.0 (64-bit) on Ubuntu 22.04

**Comment by bradenhilton** [comment] 2023-08-16 20:09
Okay, I'm a little all over the place at the moment investigating this and https://github.com/twpayne/chezmoi/issues/3180, but I must express my confusion.

My current working copy for https://github.com/twpayne/chezmoi/issues/3180 **without switching to the native Mermaid like I did in https://github.com/twpayne/chezmoi/pull/3177** gives this:

![Screen Shot 2023-08-16 at 20 14 27](https://github.com/twpayne/chezmoi/assets/23157013/8b0f5e3e-c9f5-4f20-ad5a-ac5e5dfa368e)

Navigating to the [same page on the live site](https://www.chezmoi.io/user-guide/command-overview/#daily-commands) still shows it incorrectly, and the browser console shows the error <br> `Uncaught ReferenceError: mermaidAPI is not defined`.

**Comment by halostatue** [comment] 2023-08-16 20:47
It’s not just that the two statements are separate, but that the `initialize` is being called as `mermaidAPI` but it is imported as `mermaid`. I can’t find anything in the configuration or anything else that should be calling it `mermaidAPI`, so something extra has happened here.

**Comment by bradenhilton** [comment] 2023-08-16 21:08
@halostatue `mermaidAPI` is defined in the module:

```javascript
u = {
  startOnLoad: !0,
  mermaidAPI: m,
  parse: z,
  render: O,
  init: C,
  run: v,
  registerExternalDiagrams: I,
  initialize: L,
  parseError: void 0,
  contentLoaded: b,
  setParseErrorHandler: $,
  detectType: P
};
export {
  u as default
};
```

This could be related to the regression mentioned in https://github.com/fralau/mkdocs-mermaid2-plugin/commit/32ca519c4cd4315a6ef7a1cacd0d92cd9003c1f6 from 2023-08-09T09:17:04Z.

The website was last built 2023-08-06T18:44:45Z.

**Comment by twpayne** [comment] 2023-08-16 21:14
Website history is in [the `gh-pages` branch](https://github.com/twpayne/chezmoi/tree/gh-pages).

@bradenhilton feel free to run `mkdocs gh-deploy` if it is helpful: you can always force-push to reset the branch to a previous commit if anything unexpected happens.

**Comment by halostatue** [comment] 2023-08-16 21:19
> @halostatue `mermaidAPI` is defined in the module:
> 
> ```js
> u = {
>   startOnLoad: !0,
>   mermaidAPI: m,
>   parse: z,
>   render: O,
>   init: C,
>   run: v,
>   registerExternalDiagrams: I,
>   initialize: L,
>   parseError: void 0,
>   contentLoaded: b,
>   setParseErrorHandler: $,
>   detectType: P
> };
> export {
>   u as default
> };
> ```

That would mean that the `import` needs to be `import { mermaidAPI } …` or the initialization needs to be `mermaid.mermaidAPI`. So there is something *really* weird being generated. This may simply be a generation error, as you’re surmising, or it could be the regression fixed in 1.0.8.

**Comment by twpayne** [comment] 2023-08-16 21:39
Sometimes dependencies break. Sometimes the right course of action is to sit back and wait until the maintainers fix the problem.

The issues here are not specific to chezmoi's use of mermaid in chezmoi's mkdocs documentation.

Zero stress. Feel free to wait this one out.

**Comment by bradenhilton** [comment] 2023-08-16 22:24
@twpayne I don't believe `mkdocs gh-deploy` will work for me on the current master, due to the symlink and path issues outlined in https://github.com/twpayne/chezmoi/issues/3180 breaking the Links templates.

I'll open the PR now to get that solved first.

**Comment by bradenhilton** [comment] 2023-08-22 07:41
@FreeMasen This was a dependency issue which is now fixed on the latest build of the website.

**Closed by bradenhilton** 2023-08-22 07:41 UTC
Labels: bug
