### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by mfxmfx** [twpayne/chezmoi#289] opened 2019-05-15 20:40 UTC
Might be a problem in the `go.mod` file:

```
$ go version
go version go1.12.5 linux/amd64

$ go get -u github.com/twpayne/chezmoi 
# github.com/twpayne/chezmoi/lib/chezmoi
go/src/github.com/twpayne/chezmoi/lib/chezmoi/loggingmutator.go:97:5: unknown field 'Colored' in struct literal of type difflib.UnifiedDiff
```

**Comment by twpayne** [comment] 2019-05-15 20:41
You need to build with GO111MODULE=on.

**Comment by mfxmfx** [comment] 2019-05-15 20:51
Thanks, but this does not seem to help:

```
$ GO111MODULE=on go get -u github.com/twpayne/chezmoi
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/sys latest
go: finding github.com/zalando/go-keyring latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/crypto latest
go: finding github.com/armon/consul-api latest
go: finding golang.org/x/net latest
go: finding golang.org/x/tools latest
go: finding github.com/ugorji/go/codec latest
go: finding gopkg.in/check.v1 latest
go: finding golang.org/x/lint latest
go: finding golang.org/x/exp latest
go: finding google.golang.org/genproto latest
go: finding golang.org/x/time latest
go: finding honnef.co/go/tools latest
go: finding github.com/golang/glog latest
go: finding github.com/google/pprof latest
go: finding golang.org/x/image latest
go: finding github.com/BurntSushi/xgb latest
go: finding github.com/jstemmer/go-junit-report latest
go: finding golang.org/x/mobile latest
# github.com/twpayne/chezmoi/lib/chezmoi
go/pkg/mod/github.com/twpayne/chezmoi@v1.5.1/lib/chezmoi/loggingmutator.go:97:5: unknown field 'Colored' in struct literal of type difflib.UnifiedDiff
```

**Comment by twpayne** [comment] 2019-05-15 20:58
Hmm, it looks like the replacement difflib is not being used. See https://github.com/twpayne/chezmoi/blob/master/go.mod#L41-L43. I'm not sure why it's not building for you, it is building on Travis CI.

**Comment by mfxmfx** [comment] 2019-05-15 21:00
Does running `go mod tidy` on your machine make any changes?

**Comment by mfxmfx** [comment] 2019-05-15 21:10
BTW, I get the same error with the following `Dockerfile`:

```
FROM golang:1.12

USER root

# WARNING: runs as root
RUN env GO111MODULE=on go get -u github.com/twpayne/chezmoi 
```
Output:

```
[...]
go: extracting golang.org/x/text v0.3.2
# github.com/twpayne/chezmoi/lib/chezmoi
pkg/mod/github.com/twpayne/chezmoi@v1.5.1/lib/chezmoi/loggingmutator.go:97:5: unknown field 'Colored' in struct literal of type difflib.UnifiedDiff
```

**Comment by twpayne** [comment] 2019-05-15 22:10
`go mod tidy` does not result in any changes on my machine. I've just added a check for this in #290, which indicates that `go.mod` and `go.sum` are up-to-date.

The `Dockerfile` does reproduce the problem, however. I don't understand why this error occurs yet - it looks like Go is downloading the wrong `go-difflib` module. I'll investigate.

**Comment by twpayne** [comment] 2019-05-15 22:29
OK, so if you checkout the source, the build works. `go get -u` is ignoring the `replace` directives in `go.mod`.

The underlying problem seems to be:
1. chezmoi relies on a couple of patched packages. In one case (`github.com/pmezard/go-difflib`) this is because the upstream has been abandoned, and in the second case (`github.com/etcd-io/bbolt`) is because I'm waiting for a PR to be merged.
2. chezmoi uses a `replace` directive in `go.mod` to override these packages with the patched versions.
3. Specifically, `go-difflib` is only used in a sub package `./lib/chezmoi` which is a dependency of the main package.
3. `go get -u` ignores `replace` directives in `go.mod` files for its dependencies.
4. Therefore `go get -u` tries to build `./lib/chezmoi` with the incorrect modules.

I suspect that the Go authors have a good reason for this behavior (although I have no idea what that reason is when the dependency is a subpackage of the main package). Obviously Go isn't going to be fixed for a long time so I'll rewrite some import paths to work around this.

**Comment by twpayne** [comment] 2019-05-15 23:02
This should now be fixed with #291. I've tested it with the `Dockerfile` and it now works for me.

Thanks very much for reporting the bug and giving the exact code to reproduce it - much appreciated.

**Closed by twpayne** 2019-05-15 23:02 UTC
Labels: bug

**Comment by mfxmfx** [comment] 2019-05-15 23:30
Many thanks for the quick fix!

And thanks for chezmoi - this looks very promising, and now that I can build it I can finally play around with it :smile: 

P.S. you might want to update `docs/INSTALL.md` to read `env GO111MODULE=on go get -u github.com/twpayne/chezmoi`

**Comment by mfxmfx** [comment] 2019-05-16 09:55
Link to the go.mod replace issue, just for the records: https://github.com/golang/go/issues/31173
