### ISSUE TITLE
`chezmoi apply --dry-run --verbose` fails with script and invalid template

### ISSUE THREAD

**Issue by KapJI** [twpayne/chezmoi#3995] opened 2024-10-15 14:49 UTC
## Describe the bug

I added template which can't be rendered because it calls uninstalled tool. Abd sThen I run `chezmoi apply --dry-run --verbose`. With `delta` pager I have invalid characters printed to terminal. With the default pager terminal blinks and error message is printed only sometimes.

This doesn't happen on Windows.

## To reproduce

Add invalid template:
```
{{- output "uninstalled_tool" -}}
```

Add new empty script `.chezmoiscripts/run_before_test.sh`:
```sh
#!/bin/sh
```

With `delta` pager:
```toml
[diff]
pager = "delta"
```

On MacOS some random control characters are printer to terminal and there is `Screen.Init()` error:
```console
$ chezmoi apply --dry-run -v
chezmoi: .config/zsh/custom_completion/_ruff: template: dot_config/zsh/custom_completion/_ruff.tmpl:1:4: executing "dot_config/zsh/custom_completion/_ruff.tmpl" at <output "ruff" "generate-shell-completion" "zsh">: error calling output: ruff generate-shell-completion zsh: exec: "ruff": executable file not found in $PATH
Error: Screen.Init(): input/output error

$ chezmoi apply --dry-run -v
chezmoi: .config/zsh/custom_completion/_ruff: template: dot_config/zsh/custom_completion/_ruff.tmpl:1:4: executing "dot_config/zsh/custom_completion/_ruff.tmpl" at <output "ruff" "generate-shell-completion" "zsh">: error calling output: ruff generate-shell-completion zsh: exec: "ruff": executable file not found in $PATH
Error: Screen.Init(): input/output error

$
/64;1;2;4;6;17;18;21;22c_
```

On Linux there is only `Error: Screen.Init(): input/output error` error.

On MacOS with default pager terminal is blinking and error message is printed only for some calls:
```
$ chezmoi apply --dry-run -v
chezmoi: .config/zsh/custom_completion/_ruff: template: dot_config/zsh/custom_completion/_ruff.tmpl:1:4: executing "dot_config/zsh/custom_completion/_ruff.tmpl" at <output "ruff" "generate-shell-completion" "zsh">: error calling output: ruff generate-shell-completion zsh: exec: "ruff": executable file not found in $PATH
$ chezmoi apply --dry-run -v
$ chezmoi apply --dry-run -v
$ chezmoi apply --dry-run -v
$ chezmoi apply --dry-run -v
$ chezmoi apply --dry-run -v
$ chezmoi apply --dry-run -v
$ chezmoi apply --dry-run -v
chezmoi: .config/zsh/custom_completion/_ruff: template: dot_config/zsh/custom_completion/_ruff.tmpl:1:4: executing "dot_config/zsh/custom_completion/_ruff.tmpl" at <output "ruff" "generate-shell-completion" "zsh">: error calling output: ruff generate-shell-completion zsh: exec: "ruff": executable file not found in $PATH
```

On Linux with default pager it mostly works but terminal output looks corrupted with `(END)%` at the end:
```console
$ chezmoi apply --dry-run -v
diff --git a/.chezmoiscripts/test.sh b/.chezmoiscripts/test.sh
new file mode 100755
index 0000000000000000000000000000000000000000..13f47935d98bc44bbe5f7dafb745814aab2b8b79
--- /dev/null
+++ b/.chezmoiscripts/test.sh
@@ -0,0 +1,2 @@
+#!/bin/sh
+
chezmoi: .testfile.txt: template: dot_testfile.txt.tmpl:1:4: executing "dot_testfile.txt.tmpl" at <output "uninstalled_tool">: error calling output: uninstalled_tool: exec: "uninstalled_tool": executable file not found in $PATH
(END)%

OA
OA: command not found
```

* Without `-v` it works as expected.
* Without script it works as expected.
* Without broken template it works as expected.

## Expected behavior

Error message is printed every time, terminal doesn't blink and not corrupted.

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor

RESULT    CHECK                       MESSAGE
ok        version                     v2.52.3, commit c136cd0324b46d311427eaf8ebff3d4532effbb1, built at 2024-09-30T09:03:56Z, built by goreleaser
warning   latest-version              v2.52.4
ok        os-arch                     darwin/arm64
ok        uname                       Darwin sayfutdinov-mac 23.6.0 Darwin Kernel Version 23.6.0: Wed Jul 31 20:48:52 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6020 arm64
ok        go-version                  go1.23.1 (gc)
ok        executable                  ~/.local/bin/chezmoi
ok        upgrade-method              replace-executable
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-10-15T15:22:21+01:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/zsh
ok        cd-args                     /bin/zsh
info      diff-command                not set
ok        edit-command                found /opt/homebrew/bin/nvim
ok        edit-args                   /opt/homebrew/bin/nvim
ok        git-command                 found /usr/local/bin/git, version 2.39.3
ok        merge-command               found /opt/homebrew/bin/nvim
ok        shell-command               found /bin/zsh
ok        shell-args                  /bin/zsh
info      age-command                 age not found in $PATH
ok        gpg-command                 found /opt/homebrew/bin/gpg, version 2.4.5
info      pinentry-command            not set
ok        1password-command           found /opt/homebrew/bin/op, version 2.30.0
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

## Additional context

Let me know if you need more information.

**Comment by twpayne** [comment] 2024-10-15 19:59
> `Error: Screen.Init(): input/output error`

This comes from something on your system, not from chezmoi.



> On Linux with default pager it mostly works but terminal output looks corrupted with `(END)%` at the end

This is also coming from something on your system, not from the chezmoi.

Please provide a way for someone else to reproduce the problem that you see. In the meantime, I'll close this.

**Comment by KapJI** [comment] 2024-10-16 13:11
You're right that `Screen.Init()` is not from chezmoi, it's from my pager that is crashing.

But chezmoi still does something unusual here. Basically this happens when interactive pager is used.

I installed clean VM with Ubuntu 24.04, isntalled chezmoi, then:
```console
$ chezmoi init
$ mkdir ~/.config/chezmoi
$ cat >> ~/.config/chezmoi/chezmoi.toml <<EOF
[diff]
pager = "less"
EOF
$ mkdir $(chezmoi source-path)/.chezmoiscripts
$ echo '#!/bin/sh' > $(chezmoi source-path)/.chezmoiscripts/run_before_test.sh
$ echo '{{- output "non_existing_tool" -}}' > $(chezmoi source-path)/dot_testfile.txt
$ chezmoi apply --dry-run --verbose
```

**Result:** less with diff blinks and immediately closes, error is printed, terminal session is broken completely. I can't see echo from characters I'm printing anymore, running `clear` doesn't help.

When pager is not set, it works as expected, first diff is printed, then error message.

Here is strace log if you can find something interesting there. Last 300 lines is where `less` started.
* Log: [chezmoi_strace_full.log](https://github.com/user-attachments/files/17396036/chezmoi_strace.-.full.log)
* 20169 - chezmoi main pid
* 20170-20172, 20174 - children of 20169 created by `clone3`
* 20173 - child of 20171 created by `clone3`
* 20176 - less pid

Note that all chezmoi processes exited earlier than `less`. That can explain why less exited immediately when parent died.

**Comment by twpayne** [comment] 2024-10-26 00:05
Re-opening this on the request of @KapJI in https://github.com/twpayne/chezmoi/pull/4028#issuecomment-2438866544.

I need some convincing that this is a bug in chezmoi. I suspect that it's more likely that the terminal is getting messed up because too many programs are trying to control it and are conflicting with each other.

**Comment by KapJI** [comment] 2024-10-30 13:27
Basically, as I mentioned on #4028, `persistentPostRunRootE` is never executed when `applycmd` returns an error.  Because of that pager process is not waited and bug occurs.

I found there is an issue in cobra about this: https://github.com/spf13/cobra/issues/1893

I think chezmoi needs to ensure `persistentPostRunRootE` is always run. Proposed solution is moving `persistentPostRunRootE` to `cobra.OnFinalize`.

Simplified (and fixed typo) repro:

```console
$ chezmoi init
$ mkdir -p ~/.config/chezmoi
$ cat >> ~/.config/chezmoi/chezmoi.toml <<EOF
[diff]
pager = "less"
EOF
$ echo '#!/bin/sh' > $(chezmoi source-path)/run_before_test.sh
$ echo '{{- output "non_existing_tool" -}}' > $(chezmoi source-path)/dot_testfile.txt.tmpl
$ chezmoi apply --dry-run --verbose
```

**Closed** 2024-10-30 15:06 UTC
Labels: investigating
