### ISSUE TITLE
using chezmoiignore

### ISSUE THREAD

**Issue by richukuttan** [twpayne/chezmoi#1237] opened 2021-05-28 07:41 UTC
## What exactly are you trying to do?

Ignore the bitwarden config file (~/.config/Bitwarden\ CLI/*)

## What have you tried so far?

Attempt 1: Add ".config/Bitwarden\ CLI/\*" to  $(chezmoi source-path)/.chezmoiignore
Attempt 2: Add ".config/Bitwarden\ CLI/\*\*" to  $(chezmoi source-path)/.chezmoiignore
Attempt 3: Add ".config/Bitwarden\ CLI/\*\*/\*" to  $(chezmoi source-path)/.chezmoiignore
Attempt 4: Add ".config/Bitwarden\ CLI/\*\*/\*" to  $(chezmoi source-path)/.chezmoiignore
Attempt 4: Add ".config/\*\*" to  $(chezmoi source-path)/.chezmoiignore
Attempt 5: Add "private_dot_config/private_Bitwarden\ CLI/\*" to  $(chezmoi source-path)/.chezmoiignore
Attempt 6: Add private_dot_config/private_Bitwarden\ CLI/\*\*" to  $(chezmoi source-path)/.chezmoiignore
Attempt 7: Add private_dot_config/private_Bitwarden\ CLI/\*\*/\*" to  $(chezmoi source-path)/.chezmoiignore

## Where else have you checked for solutions?

* [ x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [ x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [ x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose`

```
$ chezmoi add .config --verbose
...
diff --git a/private_dot_config b/private_dot_config
new file mode 40755
index 0000000000000000000000000000000000000000..e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
--- /dev/null
+++ b/private_dot_config
diff --git a/private_dot_config/private_Bitwarden CLI b/private_dot_config/private_Bitwarden CLI
new file mode 40755
index 0000000000000000000000000000000000000000..e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
--- /dev/null
+++ b/private_dot_config/private_Bitwarden CLI
diff --git a/private_dot_config/private_Bitwarden CLI/private_data.json b/private_dot_config/private_Bitwarden CLI/private_data.json
new file mode 100644
index 0000000000000000000000000000000000000000..c42e5f26ade1c27b623d2bda58fcc3a918715866
--- /dev/null
+++ b/private_dot_config/private_Bitwarden CLI/private_data.json
<contents of the file>
...
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.0.12, commit 2256a83c51b97f4a326feb66fd3ebdc3f1833a15, built at 2021-05-10T22:46:04Z, built by goreleaser
ok       os-arch              linux/amd64
info     config-file          /home/hrishi/.config/chezmoi/chezmoi.toml does not exist
ok       source-dir           /home/hrishi/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries found in /home/hrishi/.local/share/chezmoi
ok       dest-dir             /home/hrishi is a directory
ok       shell                found /usr/bin/fish
ok       editor               found /usr/bin/vi
ok       git-cli              found /usr/bin/git, version 2.31.1
ok       merge-cli            found /usr/bin/vimdiff
ok       age-cli              age not found in $PATH
ok       gnupg-cli            found /usr/bin/gpg, version 2.2.27
info     1password-cli        op not found in $PATH
ok       bitwarden-cli        found /home/hrishi/bin/bw, version 1.16.0
info     gopass-cli           gopass not found in $PATH
info     keepassxc-cli        keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-cli         lpass not found in $PATH
info     pass-cli             pass not found in $PATH
info     vault-cli            vault not found in $PATH
info     secret-cli           not set
```

**Comment by twpayne** [comment] 2021-05-28 09:27
It's not necessary to escape the space with `\`. Try:

    .config/Bitwarden CLI
    .config/Bitwarden CLI/**

to ignore the `.config/Bitwarden CLI` directory and everything in it.

**Comment by richukuttan** [comment] 2021-05-28 10:17
That doesn't work either. Unlike the output of [721](https://github.com/twpayne/chezmoi/issues/721l), I do not see any warning about files being skipped either.

Since I'm just starting to create my dotfiles, I'm trying to get this right by removing the local chezmoi folder and reinitializing it. This is what I'm doing to check:

`
>rm -rf ~/.local/share/chezmoi
>chezmoi init
>echo ".config/Bitwarden CLI/" > $(chezmoi source-path)/.chezmoiignore
>echo ".config/Bitwarden CLI/**" >> $(chezmoi source-path)/.chezmoiignore
>cat (chezmoi source-path)/.chezmoiignore
.config/Bitwarden CLI/
.config/Bitwarden CLI/**
>chezmoi add .config
>ls private_dot_config/private_Bitwarden\ CLI/ | wc -l
1
`

This gives me one file in the folder. Is there some other config that saves the previous state of the bitwarden file and rewrites it when it doesn't see it? Or a better way to clean chezmoi?

**Comment by twpayne** [comment] 2021-05-28 14:20
Thanks for testing, I'll try to reproduce the problem locally.

> This gives me one file in the folder. Is there some other config that saves the previous state of the bitwarden file and rewrites it when it doesn't see it? Or a better way to clean chezmoi?

Yes. You can use `create_` files for this. They're not well documented but they do work. If you add a file called `create_dot_file` with some contents in your source directory then chezmoi will create a file called `.file` in the target directory with those contents if `.file` doesn't already exist, or leave `.file` untouched if it already exists.

**Comment by gotgenes** [comment] 2021-08-15 21:17
I had a similar question. I'm trying to prevent `chezmoi add ~/.config/nvim` from including `~/.config/nvim/plugin/packer_compiled.lua`. I tried adding `.config/nvim/plugin/packer_compiled.lua` to my `.chezmoiignore` (located at `~/.local/share/chezmoi/.chezmoiignore`), and various other patterns using `**/` globbing, however, none prevented `chezmoi add` from adding the file into the source directory.

I tried a simpler case of putting `foo` in the `.chezmoiignore` and adding a `foo` file to my home directory. `chezmoi add foo` still added `foo` to the source directory, with no warning or complaints.

I understand from #721 that `.chezmoiignore` was initially implemented for `chezmoi apply`, however, a mechanism by which to prevent `chezmoi add` from adding files to the source directory would be most welcome. Controlling the `chezmoi add` behavior is actually what I initially expected, given that would be analogous to the `.gitignore`, while the real behavior is more like the converse of `.gitignore`. (It would be like if it prevented Git from overwriting the working directory contents with contents of the index). I'm glad the latter exists (prevents my `README.md` from being put into my home directory), however, having the former would also help with the usability of `chezmoi add`.

**Comment by nkgm** [comment] 2021-12-12 09:52
>  I could also use a way to stop chezmoi add from adding certain files or directories from my home directory into the repository.

This is something I'm sorely missing as well. I have a nodejs project living in its own directory in my dotfiles (for generating a certain kind of repetitive config) and right now I can't figure out a way to `chezmoi add ~/.dotfiles` without also copying `node_modules` taking several minutes in the process. Other than manually `add`ing each and every file in `.dotfiles`, sidestepping `node_modules`, I opted to go for a full `chezmoi add ~/.dotfiles`, wait it out, create a `.gitignore` in the source directory, add/commit the files, then do a `git clean -fX` to get rid of the files that should have been ignored in the first place. Hopefully you only have to do this kind of thing once or twice so it's not all that bad, but it took me a lot of fiddling around with `.chezmoiignore` before realizing it was meant for something completely different and finding this issue.

**Comment by twpayne** [comment] 2021-12-12 22:42
`chezmoi add` will not add files that are ignored by `.chezmoiignore`. There's a [test for this](https://github.com/twpayne/chezmoi/blob/a556b93d19c12b41d46eab1d363131a460290575/internal/cmd/testdata/scripts/add.txt#L63-L66). If you have observed different behavior, please give details.

**Comment by nkgm** [comment] 2021-12-14 21:56
Please forgive any oversight as I'm new to chezmoi. My confusion partly stems from the fact I couldn't get it to work excluding directories. Here's an example:

```
.nkgm/dir/subdir/   # as suggested in docs/reference/#chezmoiignore examples
# or
**/subdir
```


```ShellSession
$ tree .nkgm/dir
/Users/nkgm/.nkgm/dir
└── subdir
    └── file

$ chezmoi add ~/.nkgm/dir
chezmoi: /Users/nkgm/.nkgm/dir/subdir/file: parent directory not in source state
```

The problem goes away for:
```
**/subdir
**/subdir/*
```
... which feels counterintuitive. We should clarify if this is intended behavior, and amend the docs accordingly.

**Comment by twpayne** [comment] 2022-03-06 22:01
#1942 adds an explicit test for the issue reported here, and passes on all operating systems. So, closing this for now. Please re-open if needed.

**Closed by twpayne** 2022-03-06 22:01 UTC
Labels: support
