### ISSUE TITLE
`chezmoi apply` misinterprets incorrect user input

### ISSUE THREAD

**Issue by sersorrel** [twpayne/chezmoi#1127] opened 2021-04-03 02:31 UTC
## Describe the bug

`chezmoi apply` silently overwrites files that have changed if the user inputs something unexpected. (imo, `q` should be recognised as well as `quit` and so on, but that's another matter)

## To reproduce

```console
$ chezmoi apply
.profile has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? q
$ # whatever the changes were, to whichever version of .profile, they're gone now
```

## Expected behavior

If something unexpected happens, the default should not be to overwrite files:

https://github.com/twpayne/chezmoi/blob/7dd00b2d19898210cd5332d71de967d69875d782/cmd/config.go#L484-L485

https://github.com/twpayne/chezmoi/blob/7dd00b2d19898210cd5332d71de967d69875d782/cmd/config.go#L491-L492

https://github.com/twpayne/chezmoi/blob/7dd00b2d19898210cd5332d71de967d69875d782/cmd/config.go#L493-L494

**Comment by twpayne** [comment] 2021-04-03 19:00
Please use the bug report template to report bugs in the future.

I'm unable to reproduce this. `q` is interpreted as quit, and overwriting is not the default:

```
$ chezmoi --version
chezmoi version v2.0.7, commit 1ce19442a526747d53317a4cd5764f4e4a60a216, built at 2021-03-31T00:22:56Z, built by homebrew
$ echo foo > ~/.tmux.conf
$ chezmoi status
MM .tmux.conf
$ chezmoi apply
.tmux.conf has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? q
$ chezmoi status
MM .tmux.conf
```

Could you provide steps to reproduce the problem?

**Comment by sersorrel** [comment] 2021-04-04 16:28
hm, possibly I misdiagnosed this, sorry. `chezmoi status` gives no output, so I assumed it'd overwritten the destination, but if I rerun `chezmoi apply`, I still get ".profile has changed since chezmoi last wrote it".

The destination and target .profile are identical:

```
$ diff .profile (chezmoi execute-template < .local/share/chezmoi/dot_profile.tmpl | psub)
$ sha256sum .profile
9e2531a8feecbd5437bc19635ef592a42369493425672819f4310198b4213605  .profile
$ sha256sum (chezmoi execute-template < .local/share/chezmoi/dot_profile.tmpl | psub)
9e2531a8feecbd5437bc19635ef592a42369493425672819f4310198b4213605  /tmp/.psub.878TdxBEKl
```

Inspecting chezmoistate.boltdb, that has a different hash listed:

```
"contentsSHA256": "adb8581e18471a4d25d9ccb14cdf5e416b8e305d07dbb6c1f1d5dab6ce865b25"
```

Could this have been caused by – given I have a `dot_profile.tmpl` in the source directory – me accidentally running `chezmoi add .profile` and creating a `dot_profile`, then deleting that and fixing up the existing `dot_profile.tmpl` by hand to match the target?

**Comment by twpayne** [comment] 2021-04-04 16:37
Thanks for the further investigation!

> Could this have been caused by – given I have a `dot_profile.tmpl` in the source directory – me accidentally running `chezmoi add .profile` and creating a `dot_profile`, then deleting that and fixing up the existing `dot_profile.tmpl` by hand to match the target?

Yes, this sounds reasonable, assuming that there was some difference between the first `.profile` written by chezmoi (as recorded in chezmoistate.boltdb) and the fixed-up `.profile` generated from `dot_profile.tmpl` (to explain the difference in checksums).

**Comment by twpayne** [comment] 2021-04-07 21:06
Closing this for now - please re-open if needed.

**Closed by twpayne** 2021-04-07 21:06 UTC
Labels: investigating
