### ISSUE TITLE
Add flag to ignore encrypted files apply 

### ISSUE THREAD

**Issue by 3v1n0** [twpayne/chezmoi#778] opened 2020-05-31 14:00 UTC
## Is your feature request related to a problem? Please describe.

Just imported my dotfiles in a server where I didn't import my secret GPG key yet, but still I'd like to import the rest of the configuration.

Right now it just fails with `gpg: decryption failed: No secret key`

## Describe the solution you'd like

Would like to have an `apply --ignore-encrypted` or something similar that can be used to apply everything but the encrypted files.

**Comment by twpayne** [comment] 2020-06-01 19:45
Thank you for your suggestion - this makes a lot of sense. I'll target this for version 2.1, which is coming closer (#654).

**Comment by 3v1n0** [comment] 2021-03-18 15:18
This isn't fixed as part of v2.0.0, right?

As I assume it's the same side of https://github.com/twpayne/chezmoi/issues/1074

**Comment by twpayne** [comment] 2021-03-18 17:37
This should be done in v2, the flag is `--exclude=encrypted`, see [this bit of the reference manual](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#-x---exclude-types).

That said, I see that there isn't a test for it, so it may not be working as intended at the moment. Re-opening this issue until it is confirmed fixed.

**Comment by 3v1n0** [comment] 2021-03-18 18:43
Ok the option work, can it be persisted in a specific machine via a local config value?

**Comment by 3v1n0** [comment] 2021-03-18 18:43
In any case i guess the error in decrypt failure should be a bit clearer :)

**Comment by twpayne** [comment] 2021-03-19 00:18
> Ok the option works, can it be persisted in a specific machine via a local config value?

Not at the moment, but you can use `.chezmoiignore` (which is a automatically interpreted as template) to ignore encrypted files on specific machines.

> In any case i guess the error in decrypt failure should be a bit clearer :)

https://github.com/twpayne/chezmoi/pull/1079/commits/966d45a71cb9185ffaf39fc920fb8a12ef24cef8 means that errors from encryption tools should now be surfaced, instead of being hidden behind `exit status 2` messages.

> That said, I see that there isn't a test for it, so it may not be working as intended at the moment. Re-opening this issue until it is confirmed fixed.

https://github.com/twpayne/chezmoi/pull/1079/commits/700db6e0e7003a92cadc5cf1f06e56186b1e328a adds tests, and they pass, so I'll close this issue.

Thanks again here for your work and feedback - this really helps :)

**Closed** 2021-03-19 09:49 UTC
Labels: enhancement
