### ISSUE TITLE
Conditional Symlinks

### ISSUE THREAD

**Issue by bascht** [twpayne/chezmoi#585] opened 2020-02-06 14:13 UTC
## What exactly are you trying to do?

Trying create a symlink **only on some** of my machines. I want to start some systemd services upon login, so I want a symlink from `~/.config/systemd/user/default.target.wants/my.service` to `~/.config/systemd/user/my.service`.

## What have you tried so far?

I tried adding a template to `.local/share/chezmoi/dot_config/systemd/user/default.target.wants/symlink_my.service`:

```jinja2
{{ if .chezmoi.hostname == "myhost" }}
~/.config/systemd/user/my.service
{{ end }}
```

Which would be the most intuitive way imho, but that only creates a broken symlink to the full template contents.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not
  found the answer.
* [x] I have read [chezmoi's
  FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not
  found the answer.
* [x] I have searched [chezmoi's reference
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and
  not found the answer.
* [x] Other, please give details.

## Output of any commands you've tried with `--verbose`

```
$ chezmoi apply --verbose
ln -sf '{{ if .chezmoi.hostname == "myhost" }}
~/.config/systemd/user/my.service
{{ end }}
' /home/bascht/.config/systemd/user/default.target.wants/my.service

$ file ~/.config/systemd/user/default.target.wants/my.service
/home/bascht/.config/systemd/user/default.target.wants/my.service: broken symbolic link to {{ if .chezmoi.hostname == "myhost" }}\012~/.config/systemd/user/my.service\012{{ end }}\012

```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
     ok: version 1.7.12, commit bed22fcb91787c0d3d2d8ca61ebfe7799380f961, built at 2020-01-24T02:30:18Z
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/bascht/.local/share/chezmoi (source directory, perm 700)
     ok: /home/bascht (destination directory, perm 700)
warning: /home/bascht/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/zsh (shell)
     ok: /usr/bin/vi (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.24.1)
     ok: /usr/bin/gpg (GnuPG, version 2.2.18)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: /home/bascht/bin/gopass (gopass CLI)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: /home/bascht/bin/pass (pass CLI)
warning: vault (Vault CLI, not found)
```

## Additional context

Let me know if I can supply more information! :)

**Comment by twpayne** [comment] 2020-02-06 15:14
Thanks for all the detailed information!

The overall approach is correct, but there are a couple of things that are causing things to break:

> I tried adding a template to `.local/share/chezmoi/dot_config/systemd/user/default.target.wants/symlink_my.service`:

To be interpreted as a template, the file in the source directory must have a `.tmpl` extension, i.e. rename `.local/share/chezmoi/dot_config/systemd/user/default.target.wants/symlink_my.service` to `.local/share/chezmoi/dot_config/systemd/user/default.target.wants/symlink_my.service.tmpl`. Without this, the file contents are interpreted literally, giving you the broken symlink to the full file contents, as you report.

> `{{ if .chezmoi.hostname == "myhost" }}`
> `~/.config/systemd/user/my.service`
> `{{ end }}`

The `~` shortcut to your home directory is interpreted by some shells but not by Linux or chezmoi. You need to use either the full path to make an absolute symlink (e.g. `/home/myuser/.config/systemd/user/my.service`) or use the appropriate number of leading `../`s to create a relative symlink.

Another way to achieve this is through the use of `.chezmoiignore` to specify that the symlink should only be created on `myhost`. Run:

    chezmoi add ~/.config/systemd/user/default.target.wants/my.service

and then add the following lines to `~/.local/share/chezmoi/.chezmoiignore`:

    {{ if .chezmoi.hostname != "myhost" }}
    .config/systemd/user/default.target.wants/my.service
    {{ end }}

Note the `!=` (not equal) in the condition.

Hope this helps!

**Comment by bascht** [comment] 2020-02-06 15:45
Hey @twpayne thanks a bunch for the quick answer and detailed explanation!! Much appreciated! The missing `.tmpl` extension makes it kind of obvious now! :man_facepalming: 

The approach via `.chezmoiignore` looks even cleaner, as I would only need one pair of ifs so I wanted to give it a try, but it looks like it doesn't like the expression:

```
$ cat ~/.local/share/chezmoi/.chezmoiignore
README.org
{{ if .chezmoi.hostname != "myhost" }}
.config/systemd/user/default.target.wants/my.service
{{ end }}%                                                                                                                                                               

$ chezmoi diff --verbose --debug
chezmoi: template: /home/bascht/.local/share/chezmoi/.chezmoiignore:2: unexpected "!" in operand
```

Am I holding it wrong :grimacing: ?

**Comment by twpayne** [comment] 2020-02-06 16:23
You're not holding it wrong, I'm mis-remembering my `text/template` syntax. It's:

```
{{ if ne .chezmoi.hostname "myhost" }}
.config/systemd/user/default.target.wants/my.service
{{ end }}
```

**Comment by bascht** [comment] 2020-02-06 16:35
:sparkles: that's it. 

I just notice a bit of a downside here. There is no way to remove untracked files now. Neither with the `.chezmoiignore` option nor with the `.tmpl` file. The latter one would just try to create an empty symlink:

```
chezmoi diff
ln -sf '' /home/bascht/.config/systemd/user/default.target.wants/my.service
```

Which makes sense given the empty file the `{{ if }}` expression leaves

**Comment by twpayne** [comment] 2020-02-06 16:38
Hmm, that looks like a bug in chezmoi. If the target of the symlink is empty then chezmoi should remove it. Can you edit your template to look like this and retry?

```
{{- if ne .chezmoi.hostname "myhost" -}}
.config/systemd/user/default.target.wants/my.service
{{- end -}}
```

Those extra `-`s tell `text/template` to strip preceding and following whitespace.

In the meantime, I'll check the code...

**Comment by bascht** [comment] 2020-02-06 16:44
Can confirm. It even happens with proper `-}}` markers or an empty file:

```
$ ls -lha  ~/.local/share/chezmoi/dot_config/systemd/user/timers.target.wants/symlink_ical2org.timer.tmpl
-rw-rw-r--. 1 bascht bascht 0 Feb  6 17:42 /home/bascht/.local/share/chezmoi/dot_config/systemd/user/timers.target.wants/symlink_ical2org.timer.tmpl

$ file ~/.local/share/chezmoi/dot_config/systemd/user/timers.target.wants/symlink_ical2org.timer.tmpl
/home/bascht/.local/share/chezmoi/dot_config/systemd/user/timers.target.wants/symlink_ical2org.timer.tmpl: empty

$ chezmoi diff
ln -sf '' /home/bascht/.config/systemd/user/timers.target.wants/ical2org.timer

**Comment by twpayne** [comment] 2020-02-06 16:56
Confirmed that chezmoi was not removing empty symlinks. #586 should fix that.

**Comment by bascht** [comment] 2020-02-06 17:00
![Screenshot-2020-02-06-180016](https://user-images.githubusercontent.com/51264/73960086-923a0d00-490a-11ea-9eca-ba3f69043bb9.png)
:ok_hand: affirmative! jeeez, you're quick :grimacing:

**Comment by twpayne** [comment] 2020-02-06 23:29
I've tagged version 1.7.13 which includes this fix. This should be on the releases page in about 15 minutes.

Thanks for all your detailed reports here - it made tracking down the bugs quick and easy.

I'll close this issue for now. Please re-open it if the problem isn't completely solved.

**Closed by twpayne** 2020-02-06 23:29 UTC
Labels: support

**Comment by twpayne** [comment] 2020-02-07 00:41
Oops, it seems something has broken in the release of snaps, which means that the 1.7.13 release process did not complete successfully. If you need a new version of chezmoi to continue, please re-open this issue.

**Comment by bascht** [comment] 2020-02-07 14:23
:sparkles: thank you!

**Comment by twpayne** [comment] 2020-02-13 01:59
https://github.com/twpayne/chezmoi/releases/tag/v1.7.13 is now released and includes this fix.
