### ISSUE TITLE
chezmoi data file does not exist

### ISSUE THREAD

**Issue by truesilver92** [twpayne/chezmoi#550] opened 2020-01-07 19:34 UTC
When running `chezmoi -v data` or `chezmoi data` chezmoi comes back
with 

`chezmoi: file does not exist`

I was just trying to have chezmoi print out the json data that my
templates can use. It was a way to check that my changes to
`.config/chezmoi/chezmoi.toml` are working correctly (well actually my
changes to `.chezmoi.toml.tmpl`)

I used `chezmoi init` to test the template for the config file, and the config file it generated looks fine to me (edited for privacy)

```toml
# -*- mode: conf-unix; -*-






[data]
    email = "j@example.com"
    gpg_default_key = "9A"
    vm = "y"
    wayland = "n"
```

Any advice for figuring out which file chezmoi can't find?

**Comment by twpayne** [comment] 2020-01-07 19:38
Oops, sorry about that. I suspect that chezmoi is failing to find your config file. Could you run the following and post the output here:

    find $HOME | grep chezmoi

Please check the output before posting it to make sure it doesn't leak anything private.

I suspect that chezmoi is not finding its config file, but am not sure.

**Comment by truesilver92** [comment] 2020-01-07 19:42
I cut some lines which I figured are not pertinent (such as the .git directory)

```sh
/home/joel/.config/chezmoi
/home/joel/.config/chezmoi/chezmoi.toml
/home/joel/.local/share/chezmoi
/home/joel/.local/share/chezmoi/.chezmoitemplates
/home/joel/.local/share/chezmoi/.chezmoitemplates/profile.sh
/home/joel/.local/share/chezmoi/.chezmoitemplates/sway+i3_base.tmpl
/home/joel/.local/share/chezmoi/dot_config
/home/joel/.local/share/chezmoi/dot_config/termite
/home/joel/.local/share/chezmoi/dot_config/termite/config
/home/joel/.local/share/chezmoi/dot_config/sway
/home/joel/.local/share/chezmoi/dot_config/sway/config
/home/joel/.local/share/chezmoi/dot_config/i3
/home/joel/.local/share/chezmoi/dot_config/i3/config.tmpl
/home/joel/.local/share/chezmoi/private_dot_gnupg
/home/joel/.local/share/chezmoi/private_dot_gnupg/private_gpg-agent.conf
/home/joel/.local/share/chezmoi/private_dot_gnupg/private_gpg.conf
/home/joel/.local/share/chezmoi/private_dot_gnupg/sshcontrol
/home/joel/.local/share/chezmoi/private_dot_irssi
/home/joel/.local/share/chezmoi/private_dot_irssi/config
/home/joel/.local/share/chezmoi/.chezmoi.toml.tmpl
/home/joel/.local/share/chezmoi/dot_aliases
/home/joel/.local/share/chezmoi/dot_dircolors
/home/joel/.local/share/chezmoi/dot_gitconfig.tmpl
/home/joel/.local/share/chezmoi/dot_gitignore_global
/home/joel/.local/share/chezmoi/dot_profile.tmpl
/home/joel/.local/share/chezmoi/dot_zprofile.tmpl
/home/joel/.local/share/chezmoi/dot_zshrc
/home/joel/.local/share/chezmoi/dot_zshrc.zni
/home/joel/.local/share/chezmoi/scripts
/home/joel/.local/share/chezmoi/scripts/executable_emacsclient-runner.sh
/home/joel/.local/share/chezmoi/.#.chezmoi.toml.tmpl
/home/joel/.local/share/chezmoi/#.chezmoi.toml.tmpl#
/home/joel/#.chezmoi.toml.tmpl#
```

**Comment by truesilver92** [comment] 2020-01-07 19:54
I think I found the error. I changed/corrected the 

`/home/joel/.local/share/chezmoi/.chezmoitemplates/profile.sh` 

(I think it had incorrect syntax in it) after trying to `chezmoi apply`. `chezmoi apply` gave a much better error message

`chezmoi: template: profile.sh:33:6: executing "profile.sh" at <.ao>: map has no entry for key "ao"`

Though I am not entirely sure that `chezmoi data` was effected by it

**Comment by twpayne** [comment] 2020-01-07 20:54
Thanks for doing this investigation. I think this has exposed a couple of problems in chezmoi:

- A bug in a template was reported as a `file does not exist` error. chezmoi should do better at surfacing the underlying error cause.
- The template bug should not affect the output of `chezmoi data`.

**Comment by twpayne** [comment] 2020-01-10 21:02
> The template bug should not affect the output of chezmoi data.

This is fixed with #557.

> A bug in a template was reported as a file does not exist error. chezmoi should do better at surfacing the underlying error cause.

I'm not able to reproduce this at moment. If you have a test case, please re-open this issue.

Thanks again for reporting these issues - it all helps make chezmoi better.

**Closed by twpayne** 2020-01-10 21:02 UTC
Labels: bug

**Comment by iopsthecloud** [comment] 2020-03-31 15:29
hi there

I've a similar issue when I try to do "chezmoi add".

```
chezmoi add ~/.oh-my-zsh/plugins/fabric/fabric.plugin.zsh
chezmoi: file does not exist
```
and

```
cat /home/rerak/.oh-my-zsh/plugins/fabric/fabric.plugin.zsh

```
which is empty...

I've several example with the same issue, empty *.zsh file raise a "chezmoi: file does not exist"

**Comment by twpayne** [comment] 2020-03-31 16:16
@iopsthecloud I vaguely remember fixing a bug related to this recently. Which version of chezmoi are you using?

**Comment by iopsthecloud** [comment] 2020-03-31 16:52
@twpayne 

> chezmoi version 1.7.18, commit 8284da771e8db09a6b9a4651154bb5f7820a62f0, built at 2020-03-29T15:23:53Z, built by goreleaser

**Comment by twpayne** [comment] 2020-03-31 16:58
OK, thanks. That's the very latest version. Could you open a [new bug report](https://github.com/twpayne/chezmoi/issues/new?assignees=&template=03_bug_report.md&title=) so I can get as much data to debug this please?

**Comment by twpayne** [comment] 2020-03-31 22:48
@truesilver92 I think #649 fixes the problem that you originally reported. See the description in the PR to get the explanation.

Thanks again both of you for reporting these problems - this really helps chezmoi  improve :)
