### ISSUE TITLE
No output, no error, init and apply not working on new machine

### ISSUE THREAD

**Issue by cufbas** [twpayne/chezmoi#2730] opened 2023-02-01 18:29 UTC
## Describe the bug

Nonfunctional. Commands such as chezmoi init/apply do not output anything nor do they pull from the github repo, I've tried multiple different repos, all of them named dotfiles

## To reproduce

Command chezmoi init "github username" --apply 

## Expected behavior

something like this:
Cloning into '/home/tech/.local/share/chezmoi'...
Username for 'https://github.com': <your-username> 
Password for 'https://<your-username>@github.com': 
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.

or an error of somesort

## Output of command with the `--verbose` flag

No output with the -verbose flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

RESULT    CHECK                MESSAGE
warning   version              v2.29.4, built at 2023-01-24T18:26:40Z
ok        latest-version       v2.29.4
ok        os-arch              linux/amd64 (Arch Linux)
ok        uname                Linux main 6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64 GNU/Linux
ok        go-version           go1.19.5 (gc)
ok        executable           /usr/bin/chezmoi
ok        config-file          no config file found
ok        source-dir           ~/.local/share/chezmoi is a git working tree (clean)
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a git working tree (clean)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /bin/fish
ok        cd-args              /bin/fish
info      diff-command         not set
warning   edit-command         vi not found in $PATH
ok        edit-args            vi
ok        git-command          found /usr/bin/git, version 2.39.0
ok        merge-command        found /usr/bin/vimdiff
ok        shell-command        found /bin/fish
ok        shell-args           /bin/fish
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.40
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set

<details>

```console
$ chezmoi doctor
```

</details>

## Additional context

**The only output I can get is with --debug**

2023-02-01T19:27:25+01:00 INF persistentPreRunRootE args=["chezmoi","init","https://github.com/JohnKibe/dotfiles.git","--debug"] goVersion=go1.19.5 version={"builtBy":"","commit":"","date":"2023-01-24T18:26:40Z","version":"2.29.4"}
2023-02-01T19:27:25+01:00 INF Stat component=system name=/home/cuf/.config/chezmoi/chezmoistate.boltdb
2023-02-01T19:27:25+01:00 ERR Mkdir error="mkdir /home/cuf/.local/share/chezmoi: file exists" component=system name=/home/cuf/.local/share/chezmoi perm=511
2023-02-01T19:27:25+01:00 INF Stat component=system name=/home/cuf/.local/share/chezmoi
2023-02-01T19:27:25+01:00 ERR Mkdir error="mkdir /run/user/1000: file exists" component=system name=/run/user/1000 perm=448
2023-02-01T19:27:25+01:00 INF Stat component=system name=/run/user/1000
2023-02-01T19:27:25+01:00 INF Stat component=system name=/home/cuf/.local/share/chezmoi/.git
2023-02-01T19:27:25+01:00 ERR Mkdir error="mkdir /home/cuf/.local/share/chezmoi: file exists" component=system name=/home/cuf/.local/share/chezmoi perm=511
2023-02-01T19:27:25+01:00 INF Stat component=system name=/home/cuf/.local/share/chezmoi
2023-02-01T19:27:25+01:00 ERR ReadFile error="open /home/cuf/.local/share/chezmoi/.chezmoiroot: no such file or directory" component=system data= name=/home/cuf/.local/share/chezmoi/.chezmoiroot size=0
2023-02-01T19:27:25+01:00 INF Stat component=system name=/home/cuf/.local/share/chezmoi/.git
2023-02-01T19:27:25+01:00 ERR ReadFile error="open /home/cuf/.local/share/chezmoi/.chezmoiversion: no such file or directory" component=system data= name=/home/cuf/.local/share/chezmoi/.chezmoiversion size=0
2023-02-01T19:27:25+01:00 ERR ReadFile error="open /home/cuf/.local/share/chezmoi/.chezmoiroot: no such file or directory" component=system data= name=/home/cuf/.local/share/chezmoi/.chezmoiroot size=0
2023-02-01T19:27:25+01:00 INF ReadDir component=system name=/home/cuf/.local/share/chezmoi
2023-02-01T19:27:25+01:00 ERR Mkdir error="mkdir /home/cuf/.config/chezmoi: file exists" component=system name=/home/cuf/.config/chezmoi perm=511
2023-02-01T19:27:25+01:00 INF Stat component=system name=/home/cuf/.config/chezmoi
2023-02-01T19:27:25+01:00 INF Delete bucket=configState component=persistentState key=configState
2023-02-01T19:27:25+01:00 INF Close component=persistentState

Thank you for your time

**Comment by twpayne** [comment] 2023-02-01 21:42
There is not enough information in your report to reproduce the problem. Also thousands of people use chezmoi on a daily basis, so this is almost certainly a problem with your machine or your configuration and not a bug in chezmoi.

What is the exact command that you run? Please copy and paste the exact commands and their output here.

What is the contents of your `~/.local/share/chezmoi` directory?

**Comment by twpayne** [comment] 2023-02-01 22:32
Note that `chezmoi init`, when you already have `~/.local/share/chezmoi` checked out and your config file template is up-to-date, does nothing.

Note also that `chezmoi apply` does not print anything unless you specify the `--verbose` flag. Even if you specify the `--verbose` flag, if all your dotfiles are up-to-date, the `chezmoi apply` does not print anything.

**Comment by cufbas** [comment] 2023-02-03 15:08
> There is not enough information in your report to reproduce the problem. Also thousands of people use chezmoi on a daily basis, so this is almost certainly a problem with your machine or your configuration and not a bug in chezmoi.

I would agree

> What is the exact command that you run? Please copy and paste the exact commands and their output here.

chezmoi init --apply $GITHUB_USERNAME --verbose

chezmoi init --apply cufbas --verbose

and 

chezmoi init --apply https://github.com/cufbas/dotfiles.git --verbose

All resulted in the same behavior. Which is no output. Nothing in the terminal and nothing in ~/.local/share/chezmoi 

I got it working by cloning the dotfiles into ~/.local/share/chezmoi and just running 
chezmoi apply

I have tried this on two machines with 3 instances of arch.

>What is the contents of your ~/.local/share/chezmoi directory?

This is actually interesting. 
Running ls -a shows the directory is completely empty
but after running any of the above commands it creates a .git directory, so it must be trying to do something

Cheers

**Comment by cufbas** [comment] 2023-02-03 15:10
>Note that chezmoi init, when you already have ~/.local/share/chezmoi checked out and your config file template is up-to-date, does nothing.

Just to be clear. Does it check the home directory or just ~/.local/share/chezmoi ?

**Comment by twpayne** [comment] 2023-02-03 15:15
> Just to be clear. Does it check the home directory or just ~/.local/share/chezmoi ?

It checks `~/.local/share/chezmoi` and `~/.config/chezmoi`. It doesn't change any other files in your home directory. To check your dotfiles in your home directory, use `chezmoi status`, `chezmoi diff`, or `chezmoi apply -nv`.

**Comment by twpayne** [comment] 2023-02-03 15:23
For info, I was able to setup your dotfiles in an empty machine with these commands:

```
docker run -it archlinux:latest
[root@00841c1098aa /]# cd
[root@00841c1098aa ~]# pacman -Sy --noconfirm chezmoi
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
resolving dependencies...
looking for conflicting packages...

Package (1)        New Version  Net Change  Download Size

community/chezmoi  2.29.4-1      30.77 MiB       8.06 MiB

Total Download Size:    8.06 MiB
Total Installed Size:  30.77 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 chezmoi-2.29.4-1-x86_64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
installing chezmoi...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[root@00841c1098aa ~]# chezmoi init --apply cufbas
[root@00841c1098aa ~]# ls -a
.  ..  .Xresources  .bashrc  .config  .local  .vim  .vimrc  .xinitrc  .xmonad  dotfiles
[root@00841c1098aa ~]# 
```

**Comment by cufbas** [comment] 2023-02-03 15:34
Do you have any interest in figuring out why chezmoi is behaving like this on a fresh install or should we close this issue here?

**Comment by twpayne** [comment] 2023-02-03 16:32
I'm keen to understand what's going on.

Some things to check:
* chezmoi checks for the existence of `~/.local/share/chezmoi/.git`. If this doesn't already exist then chezmoi will run either `git init` (if you didn't pass an argument to `chezmoi init`) or `git clone` (if you did pass an argument to `chezmoi init`).
* chezmoi will use a binary called `git` if it can find it in your `$PATH`. If it can't find a `git` binary then it falls back to using its own internal implementation of git.

The behavior you've observe are consistent with having a `git` binary in your `$PATH` that does not actually clone repos. This is one possibility, there are of course numerous others.

Can you reproduce the behavior you've seen in a fresh install, e.g. in a docker container?

Do you see the same behavior if you run `chezmoi init --use-builtin-git ...`?

**Comment by twpayne** [comment] 2023-02-11 18:09
As the original issue is resolved, I'll close this now. Please re-open this issue if you find a way to reproduce it.

**Closed by twpayne** 2023-02-11 18:09 UTC
Labels: support
